### ISSUE TITLE
'from collections import Iterable' throws ImportError (Python 3.10)

### ISSUE THREAD

**Issue by klim-** [TUD-RST/symbtools#13]
In Python 3.10 `from collections import Iterable` in `core.py` throws `ImportError` and should be `from collections.abc import Iterable` instead.

**Comment by cknoll** [comment]
The bug was induced due to a refactoring of the python standard library. I created a new release on [pypi (v0.3.3)](https://pypi.org/project/symbtools/0.3.3/#history) where the bug should be fixed, see https://cloud.drone.io/TUD-RST/symbtools/24 (works for python3.10).

Please reopen if the problem persists.
